### ISSUE TITLE
Help channel: The underlining of Description suggests a link, but it is plain text

### ISSUE THREAD

**Issue by TeeVeeEss** [iota-community/optimus-bot#8]
![afbeelding](https://user-images.githubusercontent.com/17521100/183291631-20a6a5fe-1ea5-403b-b1b8-de2776d74f83.png)

**Comment by antonionardella** [comment]
Fixed by https://github.com/iota-community/optimus-bot/commit/3ea9aad8e3c574a53c2e88ad341a91b3978bb7ea
